### ISSUE TITLE
Surprising dot plot quantile colour

### ISSUE THREAD

**Issue by fkohrt** [mjskay/ggdist#228] opened 2024-05-02 06:56 UTC
When I create a dot plot (say, bee swarm, but doesn't matter) and colour the dots by quantile, the resulting plot was surprising to me:

```r
faithful |>
  ggplot2::ggplot(ggplot2::aes(x = eruptions)) +
  ggdist::stat_dots(
    mapping = ggplot2::aes(fill = ggplot2::after_stat(level)),
    layout = "swarm",
    side = "both",
    point_interval = ggdist::point_interval(.interval = ggdist::qi)
  ) +
  ggplot2::scale_y_continuous(NULL, breaks = NULL)
```

![](https://github.com/mjskay/ggdist/assets/12914806/70bcdc4b-b5f5-4734-a6bf-d06c376f6bd0)

The lower 2.5 % are taken up by four dots, while the upper 2.5 % are taken up by seven dots. This might be due to the fact that the data features exact duplicates, but it's still surprising.

```r
table(faithful$eruptions) |> head()
```

```
  1.6 1.667   1.7 1.733  1.75 1.783 
    1     1     1     1     6     2 
```

```r
table(faithful$eruptions) |> tail()
```

```
  4.9 4.933     5 5.033 5.067   5.1 
    2     3     1     1     1     1 
```

**Comment by mjskay** [comment] 2024-05-02 17:17
Yeah, 7 is about right:

```r
0.025 * nrow(faithful)
## [1] 6.8
```

But 4 is surprising.

The problem is due to the 6 points with value `1.75`, which happens to be exactly the lower end of the 95% interval:

```r
quantile(faithful$eruptions, 0.025)
## 2.5% 
## 1.75 
```

So I don't think there is a good solution: either you use `<` and undercount or `<=` and overcount:

```r
mean(faithful$eruptions < quantile(faithful$eruptions, 0.025))
## [1] 0.01470588
mean(faithful$eruptions <= quantile(faithful$eruptions, 0.025))
## [1] 0.03676471
```

I think the current approach is consistent with ggdist's interpretation of these bounds as endpoints of an interval, i.e. that the points at 1.75 exactly are considered to be inside the interval and not outside of it.

**Comment by mjskay** [comment] 2024-05-02 19:13
(closing unless someone has a suggestion for a better approach)

**Closed by mjskay** 2024-05-02 19:13 UTC

**Comment by fkohrt** [comment] 2024-07-25 11:48
Thanks for the explanation! I see that one always has to under- or overcount as `0.025 * nrow(faithful)` is not an integer. But wouldn't the error be smaller if one were to fill only three of the six dots with value 1.75, rather than all of them?

**Comment by mjskay** [comment] 2024-07-26 21:23
Sure, assuming the user is creating a plot where the high-level goal is to give the impression of a certain interval mass. However, the current semantics are about labeling individual data points, not about what the resulting overall impression is (since at the point of labeling the datapoints we have no way to know what kind of chart the person is making, or what the visual task they are trying to support is --- they may actually just want to know which datapoints are inside or outside the requested interval).
