### ISSUE TITLE
Adding an aesthetic changes dotplot layout

### ISSUE THREAD

**Issue by xiaoyingpu** [mjskay/ggdist#50] opened 2021-01-15 13:41 UTC
This works:

```
mtcars %>%
  ggplot(aes(mpg, factor(cyl))) + 
  stat_dots(aes(fill = factor(cyl)))
```
![image](https://user-images.githubusercontent.com/8374573/104733323-835bfd00-570c-11eb-8709-0980557e6426.png)

But this changes the layout of the dotplot and hides some dots too. Probably has to do with the `fill` aesthetic adding grouping to the data and the dot bins being created from those subgroups

```{r}
mtcars %>%
  ggplot(aes(mpg, factor(cyl))) + 
  stat_dots(aes(fill = factor(am)))  
```

![image](https://user-images.githubusercontent.com/8374573/104733469-bc946d00-570c-11eb-83ab-6eb4ea04a0e0.png)

Maybe this is a more reasonable behavior 
<img width="537" alt="image" src="https://user-images.githubusercontent.com/8374573/104733829-480dfe00-570d-11eb-8bdb-7557669dea89.png">

**Comment by mjskay** [comment] 2021-01-16 06:04
Ah I that's the intended behavior I think (unless you can convince me it should be otherwise :) ) --- different colors should create different groups when working with stat_dots since it's analogous to stat_halfeye and the like, where you want to be able to do summarization on different groups (e.g. using the `quantiles` argument) and then dodge those groups together as units.

If you are doing any summarization on the samples you should be able to use `geom_dots` instead of `stat_dots` and get the behavior you are looking for. Does that work?

**Comment by xiaoyingpu** [comment] 2021-01-16 14:35
`geom_dots` creates the same thing as `stat_dots`, which it should?

```
mtcars %>%
  ggplot(aes(mpg, factor(cyl))) + 
  geom_dots(aes(fill = factor(am)))
```

![image](https://user-images.githubusercontent.com/8374573/104814448-f03ec800-57dc-11eb-814a-9845273d9e33.png)

(I haven't thought through this yet but in terms of PGoG, there can be two versions of this dotplot with the same `ggdist` aesthetics🤔

<img width="834" alt="image" src="https://user-images.githubusercontent.com/8374573/104814417-bb327580-57dc-11eb-8c7f-3dd392681e56.png">

**Comment by mjskay** [comment] 2021-01-16 21:12
Hrm, must be a function of passing things through with stats then when it does work (like the examples in the vignettes)

As I recall from the ggplot docs the behavior you're seeing is the expected behavior though: categorical variables contribute to groups, which in geom_dots means separate groups of dots (you should see similar behavior with geom_dotplot for example). The slabinterval stuff is a bit different because it handles position_stack differently than base, but you aren't using that here, so it makes sense they're drawn on top of each other. 

If you don't want the color to contribute to grouping I think you can bypass it (maybe with group =NA or something like that?)

**Comment by xiaoyingpu** [comment] 2021-01-16 21:24
Yay `group = NA` works 

```
mtcars %>%
  ggplot(aes(mpg, factor(cyl))) + 
  geom_dots(aes(fill = factor(am), group = NA))
```

![image](https://user-images.githubusercontent.com/8374573/104823237-bd192a80-5816-11eb-83b5-d94a7c450ea7.png)

(My only quibble now is that without `group = NA`, and if the dots are drawn on top of each other without some reasonable offset, it can appear as if there are fewer dots than there are in the dataset)

**Comment by mjskay** [comment] 2021-01-16 21:29
> (My only quibble now is that without group = NA, and if the dots are drawn on top of each other without some reasonable offset, it can appear as if there are fewer dots than there are in the dataset)

Yeah fair. that's analogous to drawing area plots on top of each other though, which is what stat_slab does. I think this behavior makes sense for the semantics of ggdist but not so much for pgog.

**Comment by mjskay** [comment] 2021-02-27 23:18
closing this since this was a pgog thing that is resolved now yes?

**Closed by mjskay** 2021-02-27 23:18 UTC
