### ISSUE TITLE
Help or Feature Request: Set fill conditions dynamically

### ISSUE THREAD

**Issue by rcalinjageman** [mjskay/ggdist#81] opened 2021-06-18 16:07 UTC
I'm using ggdist to visualize minimal effect and equivalence tests, setting the fill on a distribution of expected error based on if it is inside or outside of a region of practical equivalence (ROPE).  

When all variables have the same ROPE, this is easy to do and very intuitive (thanks!):

```
rope <- 0.5
...
# Works
fill = stat(x > -rope & x < rope)
...

```

But I was hoping to allow for cases where the rope is set in SD units, and in that case, each test would have a different ROPE.  And there I run into trouble.   Inside stat, the column names in the graph data aren't recognized.  

```
my_data$rope = my_data$se * 0.5
...
# Won't work
fill = stat(x > -rope & x < rope)
...

```

I could pass values into stat manually (x > -my_data$rope), but that's nonsense.  Feels like maybe I need to pass the check to a function, but not sure what I could pass to it that would let me determine what row of data is currently being processed.

I realize this might cross the line from "feature request" to "provide me with help on my pet project"--so feel free to delete or ignore.  

```
# Here is a toy example  of what I'm working on
library(ggplot2)
library(ggdist)
library(distributional)

my_data <- data.frame(
  outcome_variable = c("SWB", "SWB", "Self_Esteem", "Self_Esteem"),
  effect_size_label = c("Intervention1 - Control", "Intervention2 - Control",
                         "Intervention1 - Control", "Intervention2 - Control"),
  effect_size = c(0, 1, 1.5, 0.2),
  se = c(0.50, 0.50, 1, 1),
  df = c(50, 50, 50, 50)
)

rope <- 0.3

my_data$rope_upper <- my_data$se * rope
my_data$rope_lower <- -my_data$rope_upper

my_plot <- ggplot2::ggplot(
  data = my_data,
  ggplot2::aes(
    x = effect_size,
    y = effect_size_label
  )
)  + ggplot2::facet_grid(cols = ggplot2::vars(outcome_variable))

my_plot <- my_plot + ggdist::stat_dist_halfeye(
  ggplot2::aes(
    dist = distributional::dist_student_t(
      df = df,
      mu = effect_size,
      sigma = se
    )
    # This fill command works
    , fill = stat(x > -rope & x < rope)
    # But I'd like to have something like
    #, fill = stat(x > rope_upper & x > rope_lower)
  )
)

my_plot
```

**Comment by mjskay** [comment] 2021-06-18 20:44
It's a really interesting problem, so thanks for posing it! At first I thought there was no easy solution. The problem is that when `stat`s are computed, variables from the original data are mapped onto aesthetic variables (like x, y, color, etc) and the `stat` is computed on those, then the result of that computation creates another data frame which is passed onto the geom. Expressions like `fill = stat(...)` act on that final data frame, and hence cannot directly access any columns of the original data frame (you can read more about this stuff [here](https://ggplot2.tidyverse.org/reference/aes_eval.html)).

**However,** it turns out (I just discovered) you can get around this in some cases (depending on the `stat`) by assigning variables from your input data to fake aesthetics. In most ggdist `stat`s (and in particular the `stat_dist_` ones) these fake aesthetics should survive the transformation pipeline and be passed on to the geom.

So one solution here is to assign your lower/upper bounds to some fake aesthetics (say `l` and `u`) and then use those in your `stat(...)` calculation:

```r
library(ggplot2)
library(ggdist)
library(distributional)

my_data <- data.frame(
  outcome_variable = c("SWB", "SWB", "Self_Esteem", "Self_Esteem"),
  effect_size_label = c("Intervention1 - Control", "Intervention2 - Control",
                         "Intervention1 - Control", "Intervention2 - Control"),
  effect_size = c(0, 1, 1.5, 0.2),
  se = c(0.50, 0.50, 1, 1),
  df = c(50, 50, 50, 50)
)

rope <- 0.3

my_data$rope_upper <- my_data$se * rope
my_data$rope_lower <- -my_data$rope_upper

my_plot <- ggplot2::ggplot(
  data = my_data,
  ggplot2::aes(
    x = effect_size,
    y = effect_size_label
  )
)  + ggplot2::facet_grid(cols = ggplot2::vars(outcome_variable))

my_plot <- my_plot + ggdist::stat_dist_halfeye(
  ggplot2::aes(
    dist = distributional::dist_student_t(
      df = df,
      mu = effect_size,
      sigma = se
    ),
    # assign bounds to fake aesthetics (`l` and `u`) so that they are available
    # after the stat has been calculated (for use in the `fill` expression)
    l = rope_lower,
    u = rope_upper,
    fill = stat(x > l & x < u)
  )
)

my_plot
```
```
## Warning message:
## Ignoring unknown aesthetics: l, u 
```
![image](https://user-images.githubusercontent.com/6345019/122614100-9ff9b980-d04b-11eb-8ba1-b6e30e3d7ebc.png)

While it does warn about unknown aesthetics I don't think this should be a problem in this case. You can always wrap the call to `ggdist::stat_dist_halfeye()` in `suppressWarnings()` if you don't want the spurious warning.

**Comment by mjskay** [comment] 2021-06-18 22:22
Also: lemme know if that helps or if you run into trouble with it. Closing for now otherwise.

**Closed by mjskay** 2021-06-18 22:22 UTC

**Comment by rcalinjageman** [comment] 2021-06-23 12:37
Wow!  Thanks.  This will work.  I appreciate the time and the help.
